# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for FishRouter Server"""

block_cipher = None

a = Analysis(
    ['app/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('static', 'static'),
        ('config.example.json', '.'),
    ],
    hiddenimports=[
        'app.main',
        'app.config',
        'app.api',
        'app.api.chat',
        'app.api.embeddings',
        'app.api.models',
        'app.api.monitor',
        'app.api.config',
        'app.backends',
        'app.backends.base',
        'app.backends.ollama',
        'app.backends.openai',
        'app.backends.anthropic',
        'app.backends.google',
        'app.core',
        'app.core.balancer',
        'app.core.ratelimit',
        'app.core.auth',
        'app.core.stats',
        'app.web',
        'app.web.dashboard',
        'uvicorn',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'fastapi',
        'httpx',
        'jinja2',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='fishrouter-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
